joaopedrodcf/yokaidex

README.md
src/App.js
src/Routes.js
src/components/Main/Main.js
src/components/Sidebar/Sidebar.js
src/components/shared/button/Button.js
src/components/shared/button/style.js
src/components/version-select/VersionSelect.js
src/components/version-select/index.js
src/components/version-select/style.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js

This adds the option to select a version of the game anytime the user want
Fixes # (issue)
Please delete options that are not relevant.

feat: Add option to select a version of the game

---

src/mocks/yokai-watch-3/yokais.js

There was some wrong information in Yokai watch 3 games that I found out when looking for yokais with element restoration or drain! We need to double check this data in the future.

fix: Information about elements in yokai watch 3

---

src/components/main/Main.js

This PR is important because it fixes the form submit when pressing enter!

fix: Prevent form submit when pressing enter

---

package.json
src/components/main/Main.js
src/components/main/style.js
src/components/shared/button/style.js
src/components/shared/input/Input.js
src/components/shared/input/index.js
src/components/shared/input/style.js
src/index.js

Add redesign to the filters layout that can be seen in the image below

feat: Add redesing to the filters layout

---

src/components/card/Card.js
src/components/card/style.js
src/components/utils/Utils.js
src/index.js
src/mocks/evolutions.js
src/mocks/index.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js
src/mocks/yokai-watch-3/yokais.js

This PR updates the layout of the evolutions to show the items when its a fusion, and show every element part of the evolution.
Also updated the information in the 3 yo-kai watch games.
Fixes #25

feat: Layout for evolutions and also update information in 3 games

---

src/components/main/style.js

The sidebar was opening when clicking on the checkboxes and that would impact user experience

fix: Sidebar opening when trying to click on checkboxes

---

src/components/main/Main.js

This MR is to correct a problem occoring live that you can see in the follwing screenshot

fix: Checkbox adding state in incorrect way

---

src/mocks/evolutions.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-3/yokais.js

This is just a simple fix to some evolutions that were not correct

fix: Evolutions from komasan and komajiro

---

src/App.js

Fix sidebar not fixed when scrollign down the page

fix: Sidebar not fixed when scrolling

---

public/CNAME

This PR adds the CNAME to the /public dir for us to have a custom domain name as explained here:
https://facebook.github.io/create-react-app/docs/deployment

feat: Add custom domain name

---

package.json

This will fix the custom domain domain not finding our files in live

fix: Custom domain name in package.json

---

public/.well-known/assetlinks.json

So this PR introduces the files necessary for the TWA

feat: Add files necessary for TWA

---

src/components/card/Card.js

Add favourite food name to yokai card
Issue closes #29

feat: Add yokai favourite food name in the table

---

src/components/card/Card.js
src/components/card/style.js
src/components/evolution/Evolution.js
src/components/evolution/index.js
src/components/evolution/style.js

This PR is a refactor from the card component to just import an evolution component

chore: Create evolution component

---

src/components/header/Header.js
src/components/header/style.js

Better clickable area in the header

feat: Better clickable area in the header

---

README.md
package.json
public/_redirects
public/index.html
src/components/header/Header.js
src/components/header/style.js

This PR as the objective of improving the SEO performance of our site.
Correcting simple problems find in https://sitechecker.pro/seo-report/https://yokaidex.com
##Problems
Description check: 36 signs (Recomended: 70-320 signs)
Title check: 8 signs (Recomended: 35-65 signs), Words: 1
H1-H6 check: H1 tag not found

feat: Improve SEO perfomance and move to netlify

---

public/_redirects

This PR has the objective of improving netlify redirects, for example accessing the subdomain and redirecting to the main domain

feat: Improve redirects netlify

---

public/_redirects
src/Routes.js

This PR has the objective of fixing the problem with not finding the  /.well-knonw/assetlinks.json in TWA

fix: Problem with /.well-knonw/assetlinks.json

---

public/robots.txt

Add robots.txt for SEO optimization

feat: Add robots.txt

---

public/_redirects

Adds index.html to fix the problem in PWA after clearing cache

feat: Redirects to index.html

---

src/components/card/Card.js
src/components/card/style.js
src/mocks/yokai-watch-3/yokais.js

This PR adds a new design to the moves section

feat: Redesign moves in yokai cards

---

src/components/card/Card.js
src/components/evolution/Evolution.js
src/components/evolution/style.js

This PR implements the new design for the evolutions

feat: Improve design evolutions

---

public/index.html
src/components/card/Card.js
src/components/card/style.js
src/components/header/style.js
src/globalStyle.js

This PR changes the font of our site to quicksand the same as our logo

WIP - feat: Change font to quicksand

---

src/components/card/Card.js
src/components/card/style.js
src/components/header/style.js
src/components/utils/Utils.js
src/mocks/elements.js
src/mocks/yokai-watch-3/yokais.js

feat: Redesign cards

---

src/components/card/Card.js
src/components/header/Header.js
src/components/main/Main.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js
src/mocks/yokai-watch-3/yokais.js

This fixes the missing tribe in filters and also somewhat fixes a problem found in a issue with the header, but it still doesn't close it because its not implementing the logic needed.
Closes #60

fix: Minor bugs in header and filters

---

src/Routes.js
src/components/about-us/AboutUs.js
src/components/about-us/index.js
src/components/about-us/style.js
src/components/header/Header.js
src/components/sidebar/Sidebar.js
src/index.js

This MR adds about us page with the disclaimer
Fixes #64

feat: Add about-us page

---

src/components/header/Header.js

I thinks this improves a lot the question of going back on header!

[chore] : header go back improvements

---

src/mocks/evolutions.js
src/mocks/yokai-watch-3/yokais.js

This fix minor issues in yokais information
Fixes #66

fix: Minor details about yokais in yo-kai watch 3

---

src/components/main/style.js

Fixes buttons next to each other
Fixes #70

fix: Buttons next each other

---

src/mocks/yokai-watch-1/equipments.js
src/mocks/yokai-watch-1/items.js
src/mocks/yokai-watch-2/equipments.js
src/mocks/yokai-watch-2/items.js
src/mocks/yokai-watch-3/equipments.js
src/mocks/yokai-watch-3/items.js

This add info about items and equipments to yokaidex

feat: Add items and equipments

---

src/mocks/foods.js
src/mocks/yokai-watch-3/yokais.js

Fixes some mistakes in the information of yo-kai watch 3
Fixes #74

fix: Information yo-kai watch 3

---

src/App.js
src/Routes.js
src/components/evolution/Evolution.js
src/components/header/Header.js
src/components/item-card/ItemCard.js
src/components/item-card/index.js
src/components/item-card/style.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-3/items.js

feat: Add item card

---

src/App.js
src/Routes.js
src/components/item-card/ItemCard.js
src/components/items/Items.js
src/components/items/index.js
src/components/items/style.js
src/components/sidebar/Sidebar.js

This adds to the page the list of equipments and items for the 3 main games, also included the search by name in each page.
Closes #30

feat: Add equipment and item lists

---

src/components/item-card/ItemCard.js
src/components/item-card/style.js
src/components/main/Main.js
src/mocks/yokai-watch-1/equipments.js
src/mocks/yokai-watch-2/equipments.js
src/mocks/yokai-watch-3/equipments.js
src/mocks/yokai-watch-3/yokais.js

This PR improves the design of item cards and also some information fixing
Closes #81

chore: Better design for item card

---

src/components/items/Items.js
src/components/items/style.js

Improve clickable are on items list

chore: Improve clickable are on items list

---

src/components/card/Card.js

fix: Missing key in map

---

src/components/card/Card.js
src/components/card/style.js
src/components/items/Items.js
src/components/items/style.js
src/mocks/index.js
src/mocks/legendarys.js
src/mocks/yokai-watch-3/yokais.js

Add yokai watch 3 seal section in yokai card

feat: Add yokai watch 3 seal section in yokai card

---

package.json
public/index.html
src/Routes.js
src/components/about-us/AboutUs.js
src/components/baffle-board/BaffleBoard.js
src/components/card/Card.js
src/components/evolution/Evolution.js
src/components/header/Header.js
src/components/item-card/ItemCard.js
src/components/items/Items.js
src/components/main/Main.js
src/mocks/evolutions.js
src/mocks/yokai-watch-3/yokais.js
yarn.lock

Add SEO optimization with react-helmet
Closes #78 #87

feat: Add SEO optimization with react-helmet

---

src/components/items/Items.js

fix: Items page endpoint

---

src/components/main/Main.js
src/components/main/style.js
src/mocks/evolutions.js
src/mocks/yokai-watch-3/yokais.js

This adds two new features to see yokais who have evolutions and also ones who are legendary
Closes #91

feat: Add new filters 'has evolution' and 'is legendary'

---

src/components/sidebar/Sidebar.js

This adds twitter link to the sidebar

feat: Add twitter link in sidebar

---

src/mocks/legendarys.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js

Add legendary yo-kai from yw1 and yw2
Closes #82

feat: Add legendary yo-kai from yw1 and yw2

---

src/components/items/Items.js
src/components/items/style.js
src/components/main/Main.js
src/components/main/style.js
src/components/shared/input/style.js

feat: Redesign yo-kais table

---

src/components/main/Main.js

fix: Missing game version on Main

---

package.json
src/components/items/Items.js
src/components/main/Main.js
yarn.lock

Improve infinite scroll
Closes #69

fix: Improve infinite scroll

---

src/components/evolution/Evolution.js
src/components/header/Header.js
src/mocks/evolutions.js

Prevent bug of going back to previous location
Closes #90

fix: Prevent bug of going back to previous location

---

src/components/sidebar/Sidebar.js

Add patreon section on sidebar

feat: Add patreon section on sidebar

---

src/components/main/Main.js
src/mocks/evolutions.js
src/mocks/filters/misc.js
src/mocks/foods.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js
src/mocks/yokai-watch-3/yokais.js

feat: Add filter for rare yokai

---

src/components/items/Items.js
src/components/main/Main.js
src/mocks/filters/misc.js
src/mocks/foods.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js
src/mocks/yokai-watch-3/yokais.js

Add filters for merican legendary, classic, deva yokais

feat: Add filters for merican legendary, classic, deva yokais

---

src/App.js
src/Routes.js
src/components/main/Main.js
src/components/main/style.js

Redesign filters to be collapsible

feat: Redesign filters to be collapsible

---

src/components/items/Items.js
src/components/items/style.js
src/components/main/Main.js
src/components/main/style.js

Improve styled components component naming

chore: Improve styled components component naming

---

public/index.html
src/components/about-us/AboutUs.js
src/components/items/Items.js
src/components/shared/google-ads/GoogleAds.js
src/components/shared/google-ads/index.js
src/components/shared/google-ads/style.js

feat: Add google ads

---

src/App.js
src/components/about-us/AboutUs.js
src/components/shared/google-ads/GoogleAds.js

feat: Add google adsense auto

---

public/index.html
src/App.js
src/components/about-us/AboutUs.js
src/components/shared/google-ads/GoogleAds.js

fix: Google ads

---

src/pages/main/Main.js

fix: Yokai card href

---

package.json
public/manifest.json
src/App.js
src/Routes.js
src/components/evolution/Evolution.js
src/components/header/Header.js
src/components/sidebar/Sidebar.js
src/components/sidebar/style.js
src/components/utils/Utils.js
src/mocks/yokai-watch-1/items.js
src/mocks/yokai-watch-2/items.js
src/mocks/yokai-watch-3/items.js
src/pages/baffle-board/BaffleBoard.js
src/pages/card/Card.js
src/pages/items/Items.js
src/pages/main/Main.js
yarn.lock

Uniformize the routes of the app

fix: Uniformize the routes of the app

---

src/Routes.js
src/components/sidebar/Sidebar.js
src/mocks/yokai-watch-1/crankakai.js
src/mocks/yokai-watch-1/items.js
src/mocks/yokai-watch-2/crankakai.js
src/mocks/yokai-watch-2/items.js
src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js
src/pages/crankakai/Crankakai.js
src/pages/crankakai/index.js
src/pages/crankakai/style.js
src/pages/item-card/ItemCard.js
src/pages/item-card/style.js
src/store/crankakai.js
src/store/index.js
src/store/store.js

This adds crankakai page to the yokaidex
Closes #79

feat: Add crankakai information

---

src/pages/item-card/ItemCard.js
src/pages/items/Items.js
src/store/baffleBoard.js
src/store/crankakai.js
src/store/items.js
src/store/yokais.js

Initial state of context based on url

fix: Initial state of context based on url

---

src/store/baffleBoard.js

fix: Baffleboard initial state

---

src/components/evolution/Evolution.js
src/components/moves/Moves.js
src/components/moves/index.js
src/components/moves/style.js
src/components/seal/Seal.js
src/components/seal/index.js
src/components/seal/style.js
src/components/stats/Stats.js
src/components/stats/index.js
src/components/stats/style.js
src/pages/about-us/AboutUs.js
src/pages/about-us/style.js
src/pages/baffle-board/BaffleBoard.js
src/pages/baffle-board/style.js
src/pages/card/Card.js
src/pages/card/style.js
src/pages/contact-us/ContactUs.js
src/pages/contact-us/style.js
src/pages/crankakai/Crankakai.js
src/pages/crankakai/style.js
src/pages/item-card/ItemCard.js
src/pages/item-card/style.js
src/pages/items/Items.js
src/pages/items/style.js
src/pages/main/Main.js
src/pages/main/style.js
src/styles/Styles.js
src/styles/index.js

chore: Improve codebase

---

src/mocks/yokai-watch-1/crankakai.js
src/mocks/yokai-watch-2/crankakai.js
src/mocks/yokai-watch-3/crankakai.js
yarn.lock

fix: Crank-a-kai prizes route

---

src/pages/yokai-card/YokaiCard.js

fix: Yokai card error in locations

---

src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js

feat: Add crankakai yokai watch 3

---

src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js

Add more crankakai information

feat: Add more crankakai information

---

src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js

feat: More crankakai 2

---

src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js

feat: Add more crankakai 3

---

src/components/big-label/BigLabel.js
src/pages/yokai-card/YokaiCard.js
src/pages/yokai-card/style.js
src/styles/Styles.js

Add label for yokai type in yokai card

feat: Add label for yokai type in yokai card

---

src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/yokais.js
src/mocks/yokai-watch-3/yokais.js

fix: Yokai label legendary

---

src/mocks/filters/index.js
src/mocks/filters/misc.js
src/mocks/filters/types.js
src/mocks/legendarys.js
src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js
src/mocks/yokai-watch-3/yokais.js
src/pages/main/Main.js
src/store/filterMain.js

feat: Add filter for types

---

src/components/seal/Seal.js
src/mocks/filters/misc.js
src/mocks/filters/types.js
src/mocks/yokai-watch-1/items.js
src/mocks/yokai-watch-1/yokais.js
src/pages/item-card/ItemCard.js
src/pages/items/Items.js
src/pages/items/style.js
src/pages/main/Main.js
src/pages/main/style.js
src/pages/yokai-card/YokaiCard.js
src/pages/yokai-card/style.js

feat: Add crank-a-kai information in each yokai card from yokai watch 1

---

src/components/sidebar/Sidebar.js
src/components/sidebar/style.js
src/components/utils/Utils.js
src/mocks/yokai-watch-1/yokais.js
src/mocks/yokai-watch-2/crankakai.js
src/mocks/yokai-watch-2/items.js
src/mocks/yokai-watch-2/yokais.js
src/pages/yokai-card/YokaiCard.js
src/pages/yokai-card/style.js

feat: Add more crankakai 4

---

src/components/header/style.js
src/mocks/yokai-watch-1/items.js
src/mocks/yokai-watch-2/items.js
src/mocks/yokai-watch-3/crankakai.js
src/mocks/yokai-watch-3/items.js
src/mocks/yokai-watch-3/yokais.js
src/pages/item-card/ItemCard.js

feat: Add more crankakai info 5

---

src/components/evolution/style.js
src/components/header/style.js
src/components/shared/toggle-switch/ToggleSwitch.js
src/components/sidebar/Sidebar.js
src/components/sidebar/style.js
src/components/stats/style.js
src/globalStyle.js
src/pages/about-us/style.js
src/pages/baffle-board/style.js
src/pages/contact-us/style.js
src/pages/crankakai/style.js
src/pages/item-card/ItemCard.js
src/pages/item-card/style.js
src/pages/items/style.js
src/pages/main/style.js
src/pages/yokai-card/style.js
src/store/theme.js
src/styles/Styles.js
yarn.lock

fix: Dark theme

---

src/store/theme.js

Dark theme state saved in local storage

fix: Dark theme state saved in local storage

---

src/components/sidebar/style.js

Selected version default on sidebar

fix: Selected version default on sidebar
